# Generated by Django 4.2.15 on 2024-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
